# This file was generated by GoReleaser. DO NOT EDIT.
cask "kswitch" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "18f22515b7d797eccf555f59dc01f5995cb86548e88cc83144ab6bb11b8a113e"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kswitch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e30aef415cfd4b198173300ba99175567a7a821ee5f5357a2e5ee2f91738e57"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kswitch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2fa6b5c192c3f63cc96b51553e8a2afb9464500f28fd3c4b063b455c71a3783"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kswitch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "de6268ef28f7be1006afa074f60241778ac307a1c8974c63f9bf15fcc32e4a3a"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kswitch_linux_arm64.tar.gz"
    end
  end

  name "kswitch"
  desc "A kubectl context switcher"
  homepage "https://github.com/MichaelSp/kswitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kswitch"

  # No zap stanza required

end
