# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-switch" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "0557457afe7675da16744a344494c684a071c9f42d61ddf8c4bea62e54869870"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e9b88999dc042637aaa1b72c634f22965ddcc9a09afeeff5e0fb20e561734e7"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "07812105e006c71e66b0f5a05b17378272cc921c412a1a9491584e7a1ac8f772"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "52a24077a261a86cb1566132a8e56e17618f90e58af7a1cba9352f4867c4775a"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_linux_arm64.tar.gz"
    end
  end

  name "kubectl-switch"
  desc "A kubectl context switcher"
  homepage "https://github.com/MichaelSp/kswitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-switch"

  # No zap stanza required

end
