# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-switch" do
  version "0.6.4"

  on_macos do
    on_intel do
      sha256 "31455bf1712fb444ed2973980eadf7756379c2b05c35a27872ff3d1b0d68e433"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fad4ab5a37efe149b6f068a961ad08e15ddb62c98224628e5fed7438133c5837"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "945f42c34fa590ccc2d67a1dea1d15d14be7b3bb0826e4bd4b22d78253169c33"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "40184811010e764b87fe6bdb5fc8dd960dd5d6c6bd6fd8c6606692c6f0c0febf"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_linux_arm64.tar.gz"
    end
  end

  name "kubectl-switch"
  desc "A kubectl context switcher"
  homepage "https://github.com/MichaelSp/kswitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-switch"

  # No zap stanza required

end
