# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-switch" do
  version "0.6.7"

  on_macos do
    on_intel do
      sha256 "7da14f8480bc1630216fd094441cb35f50a5652b298d3f0b5201f80b45141529"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc50fbb2a02898892147b29fd88e7ea823be613adab0d980bee960124e6057fd"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b9359699396fc1da4ff55be24877f3f48a7efc68e47a9a51e79746c5f6fc1de"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "383cd5fbd43d1049d09e00e2625c6065cec1781b3c6a01c1d92fb64bacca026a"
      url "https://github.com/MichaelSp/kswitch/releases/download/#{version}/kubectl-switch_linux_arm64.tar.gz"
    end
  end

  name "kubectl-switch"
  desc "A kubectl context switcher"
  homepage "https://github.com/MichaelSp/kswitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-switch"

  # No zap stanza required

end
